# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: React Deployment using Surge

on: 
 push:
   branches: [ master ]
 pull_request:
  branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name : Install Node js
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - name : Build React App
        run  : yarn build
      - name : Install Surge
        run  : npm install --global surge
      - name : Deploy Surge
        run : surge ./build  curly-plastic.surge.sh --token ${{ secrets.Surge_Token }}
